name       : yubico-pam
version    : 2.24
release    : 2
source     :
    - https://developers.yubico.com/yubico-pam/Releases/pam_yubico-2.24.tar.gz : 0326ff676e2b32ed1dda7fb5f1358a22d629d71caad8f8db52138bbf3e95e82d
license    : BSD-2-Clause
component  : security
summary    : Yubico Pluggable Authentication Module (PAM)
description: |
    The Yubico PAM module provides an easy way to integrate the Yubikey into your existing user authentication infrastructure. PAM is used by GNU/Linux, Solaris and Mac OS X for user authentication and by other specialized applications such as NCSA MyProxy.
builddeps  :
    - asciidoc
    - libykclient-devel
    - libyubikey-devel
    - openldap-devel
    - pam
    - yubikey-personalization-devel
setup      : |
    %configure --with-pam-dir=/lib/security/
build      : |
    %make
install    : |
    %make_install
